_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: newsletter_bilbomatica
defaults:
  sender: SMTPMailSystem
  formatter: php_mail
modules:
  swiftmailer:
    none:
      sender: php_mail
      formatter: swiftmailer
  simplenews:
    none:
      sender: php_mail
      formatter: swiftmailer
