<?php

use Drupal\Core\Cache\RefinableCacheableDependencyInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\hwc_crm_partners_migration\CrmPartnersCron;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;
use Drupal\workbench_access\Entity\AccessSchemeInterface;


/**
 * Implements hook_cron().
 */
function hwc_crm_partners_migration_callback_ocp(){
  Drupal::classResolver()
    ->getInstanceFromDefinition(CrmPartnersCron::class)
    ->cron('import_crm_ocp_partners');
}

function hwc_crm_partners_migration_callback_mp(){
  Drupal::classResolver()
    ->getInstanceFromDefinition(CrmPartnersCron::class)
    ->cron('import_crm_mp_partners');
}

function hwc_crm_partners_migration_callback_fop(){
  Drupal::classResolver()
    ->getInstanceFromDefinition(CrmPartnersCron::class)
    ->cron('import_crm_fop_partners');
}

function hwc_crm_partners_migration_callback_amb(){
  Drupal::classResolver()
    ->getInstanceFromDefinition(CrmPartnersCron::class)
    ->cron('import_crm_amb_partners');
}
