cache_control:
  anonymous: '/user/logout|must-revalidate, no-cache, private'
  authenticated: ''
_core:
  default_config_hash: GLswejPT_b3G9TtpI4NKwR1mhIB_-FnysNn9QKc-01w
general:
  varnish_purger: true
  varnish_server: osha-d9-stg-proxy-corp.mainstrat.com
  purger_maintenance_mode: false
  logging: '0'
  debug: '0'
  noise: ''
  secret: 2e39d07adba26de28588f0a3748f7634b16e1aa832546dbc3b470415dade6769
  grace: '10'
  page_cache_maximum_age: '604800'
available:
  enable_cache: true
  authenticated_users: false
  esi: false
  esi_purge_user_blocks: false
  excluded_urls: ''
