cache_control:
  anonymous: '/user/logout|must-revalidate, no-cache, private'
  authenticated: ''
_core:
  default_config_hash: GLswejPT_b3G9TtpI4NKwR1mhIB_-FnysNn9QKc-01w
general:
  varnish_purger: true
  varnish_server: varnish
  purger_maintenance_mode: false
  logging: '0'
  debug: '0'
  noise: ''
  secret: d72692f4bf61f0a4f974422f8d748f28ea7f49a93eb7f2c80d8fe457f7ac6dcb
  grace: '10'
  page_cache_maximum_age: '604800'
available:
  enable_cache: true
  authenticated_users: false
  esi: false
  esi_purge_user_blocks: false
  excluded_urls: ''
